/* Generated By:JavaCC: Do not edit this line. peliculasConstants.java */
package peliculas;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface peliculasConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int PLUS = 5;
  /** RegularExpression Id. */
  int MINUS = 6;
  /** RegularExpression Id. */
  int MULTIPLY = 7;
  /** RegularExpression Id. */
  int DIVIDE = 8;
  /** RegularExpression Id. */
  int AND = 9;
  /** RegularExpression Id. */
  int OR = 10;
  /** RegularExpression Id. */
  int OPEN = 11;
  /** RegularExpression Id. */
  int CLOSE = 12;
  /** RegularExpression Id. */
  int IGUAL = 13;
  /** RegularExpression Id. */
  int CONSTANTE_ACTOR = 14;
  /** RegularExpression Id. */
  int CONSTANTE_KEYWORD = 15;
  /** RegularExpression Id. */
  int CONSTANTE_DIRECTOR = 16;
  /** RegularExpression Id. */
  int LETRA = 17;
  /** RegularExpression Id. */
  int PALABRA = 18;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"&\"",
    "\"or\"",
    "\"(\"",
    "\")\"",
    "\"=\"",
    "\"actor\"",
    "\"keyword\"",
    "\"director\"",
    "<LETRA>",
    "<PALABRA>",
  };

}
