/* Generated By:JavaCC: Do not edit this line. ProyectoConstants.java */
package Proyecto;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ProyectoConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int PLUS = 5;
  /** RegularExpression Id. */
  int MINUS = 6;
  /** RegularExpression Id. */
  int MULTIPLY = 7;
  /** RegularExpression Id. */
  int DIVIDE = 8;
  /** RegularExpression Id. */
  int PARENTESIS_CERRADO = 9;
  /** RegularExpression Id. */
  int PARENTESIS_ABIERTO = 10;
  /** RegularExpression Id. */
  int DOS_PUNTOS = 11;
  /** RegularExpression Id. */
  int DOS_PUNTOS_IGUAL = 12;
  /** RegularExpression Id. */
  int IGUAL = 13;
  /** RegularExpression Id. */
  int P_RED = 14;
  /** RegularExpression Id. */
  int VAR = 15;
  /** RegularExpression Id. */
  int SITIO = 16;
  /** RegularExpression Id. */
  int ARCO = 17;
  /** RegularExpression Id. */
  int TRANSICION = 18;
  /** RegularExpression Id. */
  int UNIFORME = 19;
  /** RegularExpression Id. */
  int EXPONENCIAL = 20;
  /** RegularExpression Id. */
  int DETERMINISTICO = 21;
  /** RegularExpression Id. */
  int capacidad = 22;
  /** RegularExpression Id. */
  int FIN_RED = 23;
  /** RegularExpression Id. */
  int marcacion_i = 24;
  /** RegularExpression Id. */
  int DIGITO = 25;
  /** RegularExpression Id. */
  int NUMERO = 26;
  /** RegularExpression Id. */
  int LETRA = 27;
  /** RegularExpression Id. */
  int PALABRA = 28;
  /** RegularExpression Id. */
  int COMA = 29;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\")\"",
    "\"(\"",
    "\":\"",
    "\":=\"",
    "\"=\"",
    "\"P_RED\"",
    "\"VAR\"",
    "\"SITIO\"",
    "\"ARCO\"",
    "\"TRANSICION\"",
    "\"Uniforme\"",
    "\"Exponencial\"",
    "\"Deteministico\"",
    "\"capacidad\"",
    "\"FIN_RED\"",
    "\"marcacion_i\"",
    "<DIGITO>",
    "<NUMERO>",
    "<LETRA>",
    "<PALABRA>",
    "\",\"",
  };

}
